-- Version: v2.0.2A
-- Description: This SQL script is an upgrade for ATiM v2.0.2 to v2.0.2A and must be run against
-- an existing ATiM installation. Be sure to backup your database before running this script!

-- Update version information
UPDATE `versions` 
SET `version_number` = 'v2.0.2A', `date_installed` = CURDATE(), `build_number` = '1485'
WHERE `versions`.`id` =1;

-- Clean help bullets in participants
UPDATE structure_formats SET `flag_override_tag`='0', `language_tag`='', `flag_override_help`='0', `language_help`='', `flag_override_type`='0', `type`='', `flag_override_setting`='0', `setting`='', `flag_override_default`='0', `default`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='first_name');
UPDATE structure_formats SET `flag_override_tag`='0', `language_tag`='', `flag_override_help`='0', `language_help`='', `flag_override_type`='0', `type`='', `flag_override_setting`='0', `setting`='', `flag_override_default`='0', `default`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='last_name');
UPDATE structure_formats SET `flag_override_tag`='0', `language_tag`='', `flag_override_help`='0', `language_help`='', `flag_override_type`='0', `type`='', `flag_override_setting`='0', `setting`='', `flag_override_default`='0', `default`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='middle_name');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='sex');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='race');
UPDATE structure_formats SET `flag_override_tag`='0', `language_tag`='', `flag_override_help`='1', `language_help`='', `flag_override_type`='0', `type`='', `flag_override_setting`='0', `setting`='', `flag_override_default`='0', `default`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='participants') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Participant' AND tablename='participants' AND field='title');

-- Clean help bullets in dx_bloods
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_bloods') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='dx_date');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_bloods') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='age_at_dx');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='help_memo' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_bloods') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='notes');

-- Clean help bullets in dx_tissues
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='help_memo' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tissues') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='notes');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tissues') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='dx_date');
UPDATE structure_formats SET `flag_override_help`='1', `language_help`='' WHERE structure_id=(SELECT id FROM structures WHERE alias='dx_tissues') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='age_at_dx');

INSERT INTO i18n (`id`, `en`, `fr`) VALUES
("no identifier available", "No identifier available", "Aucun identifiant disponible"),
("this bank is being used and cannot be deleted", "This bank is being used and cannot be deleted", "Cette banque est utilisée et ne peut pas être supprimée"),
("this group is being used and cannot be deleted", "This group is being used and cannot be deleted", "Ce groupe est utilisé et ne peut pas être supprimé.");

-- Clean help bullets in participant contacts
UPDATE structure_fields SET  `structure_value_domain`=(SELECT id FROM structure_value_domains WHERE domain_name='contact_type') ,  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='contact_type';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='contact_name';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='street';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='locality';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='region';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='country';
UPDATE structure_fields SET  `language_help`='' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='mail_code';
UPDATE structure_fields SET  `language_help`='help_memo' WHERE model='ParticipantContact' AND tablename='participant_contacts' AND field='notes';

-- Eventum 923
ALTER TABLE aliquot_masters DROP KEY `unique_barcode`, ADD KEY (`barcode`);

-- Fix translation
UPDATE `i18n` SET `en` = 'Surgical/Clinical', `fr` = 'Chirurgical/Clinique'
WHERE `i18n`.`id` = 'surgical/clinical';

-- Fix language_tag error on cell culture field
UPDATE `structure_fields`
SET `language_tag` = 'detail'
WHERE `language_tag` LIKE 'Detail';

-- eventum 939
ALTER TABLE `storage_controls` ADD `horizontal_increment`  BOOLEAN NOT NULL DEFAULT true AFTER `reverse_y_numbering`; 

-- eventum 951
CREATE TABLE `coding_icdo_3`(
`code` CHAR(6) NOT NULL, 
`en_desc` VARCHAR(255) NOT NULL,
UNIQUE (`code`)
)Engine=InnoDb;

INSERT INTO `coding_icdo_3` (`code`, `en_desc`) VALUES
('8000/0', 'neoplasm, benign'),
('8000/1', 'neoplasm, uncertain whether benign or malignant'),
('8000/3', 'neoplasm, malignant'),
('8000/6', 'neoplasm, metastatic'),
('8000/9', 'neoplasm, malignant, uncertain whether primary or metastatic'),
('8001/0', 'tumor cells, benign'),
('8001/1', 'tumor cells, uncertain whether benign or malignant'),
('8001/3', 'tumor cells, malignant'),
('8002/3', 'malignant tumor, small cell type'),
('8003/3', 'malignant tumor, giant cell type'),
('8004/3', 'malignant tumor, spindle cell type'),
('8005/0', 'clear cell tumor, nos'),
('8005/3', 'malignant tumor, clear cell type'),
('8010/0', 'epithelial tumor, benign'),
('8010/1', 'carcinoma, borderline, uncertain malignant potential'),
('8010/2', 'carcinoma in situ, nos'),
('8010/3', 'carcinoma, nos'),
('8010/6', 'carcinoma, metastatic, nos'),
('8010/9', 'carcinomatosis'),
('8011/0', 'epithelioma, benign'),
('8011/3', 'epithelioma, malignant'),
('8012/3', 'large cell carcinoma, nos'),
('8013/3', 'large cell neuroendocrine carcinoma'),
('8014/3', 'large cell carcinoma with rhabdoid phenotype'),
('8015/3', 'glassy cell carcinoma'),
('8020/3', 'carcinoma, undifferentiated, nos'),
('8021/3', 'carcinoma, anaplastic, nos'),
('8022/3', 'pleomorphic carcinoma'),
('8030/3', 'giant cell and spindle cell carcinoma'),
('8031/3', 'giant cell carcinoma'),
('8032/3', 'spindle cell carcinoma, nos'),
('8033/3', 'pseudosarcomatous carcinoma'),
('8034/3', 'polygonal cell carcinoma'),
('8035/3', 'carcinoma with osteoclast-like giant cells'),
('8040/0', 'tumorlet, benign'),
('8040/1', 'tumorlet, nos'),
('8041/3', 'small cell carcinoma, nos'),
('8042/3', 'oat cell carcinoma'),
('8043/3', 'small cell carcinoma, fusiform cell'),
('8044/3', 'small cell carcinoma, intermediate cell'),
('8045/3', 'combined small cell carcinoma'),
('8046/3', 'non-small cell carcinoma'),
('8050/0', 'papilloma, nos (except papilloma of bladder M-8120/1)'),
('8050/2', 'papillary carcinoma in situ'),
('8050/3', 'papillary carcinoma, nos'),
('8051/0', 'verrucous papilloma'),
('8051/2', 'verrucous carcinoma in situ'),
('8051/3', 'verrucous carcinoma, nos'),
('8052/0', 'squamous cell papilloma, nos'),
('8052/2', 'papillary squamous cell carcinoma, non-invasive'),
('8052/3', 'papillary squamous cell carcinoma'),
('8053/0', 'squamous cell papilloma, inverted'),
('8060/0', 'squamous papillomatosis'),
('8070/1', 'squamous cell carcinoma, borderline'),
('8070/2', 'squamous cell carcinoma in situ, nos'),
('8070/3', 'squamous cell carcinoma, nos'),
('8070/6', 'squamous cell carcinoma, metastatic, nos'),
('8071/2', 'keratinizing squamous cell carcinoma, in situ'),
('8071/3', 'squamous cell carcinoma, keratinizing, nos'),
('8072/2', 'squamous cell carcinoma in- situ, non-keratinizing'),
('8072/3', 'squamous cell carcinoma, large cell, nonkeratinizing, nos'),
('8073/3', 'squamous cell carcinoma, small cell, nonkeratinizing'),
('8074/3', 'squamous cell carcinoma, spindle cell'),
('8075/2', 'squamous cell carcinoma in situ, adenoid'),
('8075/3', 'squamous cell carcinoma, adenoid'),
('8076/2', 'squamous cell carcinoma in situ with questionable stromal invasion'),
('8076/3', 'squamous cell carcinoma, microinvasive'),
('8077/2', 'squamous intraepithelial neoplasia, grade III (see coding guidelines, page 28)'),
('8078/2', 'squamous cell carcinoma in situ with horn formation'),
('8078/3', 'squamous cell carcinoma with horn formation'),
('8080/2', 'queyrat erythroplasia'),
('8081/2', 'bowen disease'),
('8082/3', 'lymphoepithelial carcinoma'),
('8083/2', 'basaloid squamous cell carcinoma in situ'),
('8083/3', 'basaloid squamous cell carcinoma'),
('8084/3', 'squamous cell carcinoma, clear cell type'),
('8090/1', 'basal cell tumor'),
('8090/2', 'basal cell carcinoma in situ'),
('8090/3', 'basal cell carcinoma, nos'),
('8091/3', 'multifocal superficial basal cell carcinoma'),
('8092/3', 'morpheic basal cell carcinoma'),
('8093/3', 'basal cell carcinoma, fibroepithelial'),
('8094/3', 'basosquamous carcinoma'),
('8095/3', 'metatypical carcinoma'),
('8096/0', 'intraepidermal epithelioma of jadassohn'),
('8097/3', 'basal cell carcinoma, nodular'),
('8098/3', 'adenoid basal carcinoma'),
('8100/0', 'trichoepithelioma'),
('8101/0', 'trichofolliculoma'),
('8102/0', 'trichilemmoma'),
('8102/3', 'trichilemmocarcnioma'),
('8103/0', 'pilar tumor'),
('8110/0', 'pilomatrixoma, nos'),
('8110/3', 'pilomatrix carcinoma'),
('8120/0', 'transitional cell papilloma, benign'),
('8120/1', 'urothelial papilloma, nos'),
('8120/2', 'transitional cell carcinoma in situ'),
('8120/3', 'transitional cell carcinoma, nos'),
('8121/0', 'schneiderian papilloma, nos'),
('8121/1', 'transitional cell papilloma, inverted, nos'),
('8121/3', 'schneiderian carcinoma'),
('8122/3', 'transitional cell carcinoma, spindle cell'),
('8123/3', 'basaloid carcinoma'),
('8124/3', 'cloacogenic carcinoma'),
('8130/1', 'papillary transitional cell neoplasm of low malignant potential'),
('8130/2', 'papillary transitional cell carcinoma, non-invasive'),
('8130/3', 'papillary transitional cell carcinoma'),
('8131/3', 'transitional cell carcinoma, micropapillary'),
('8140/0', 'adenoma, nos'),
('8140/1', 'atypical adenoma'),
('8140/2', 'adenocarcinoma in situ, nos'),
('8140/3', 'adenocarcinoma, nos'),
('8140/6', 'adenocarcinoma, metastatic, nos'),
('8141/3', 'scirrhous adenocarcinoma'),
('8142/3', 'linitis plastica'),
('8143/3', 'superficial spreading adenocarcinoma'),
('8144/3', 'adenocarcinoma, intestinal type'),
('8145/3', 'carcinoma, diffuse type'),
('8146/0', 'monomorphic adenoma'),
('8147/0', 'basal cell adenoma'),
('8147/3', 'basal cell adenocarcinoma'),
('8148/2', 'glandular intraepithelial neoplasia, grade III'),
('8149/0', 'canalicular adenoma'),
('8150/0', 'islet cell adenoma'),
('8150/1', 'islet cell tumor, nos'),
('8150/3', 'islet cell carcinoma'),
('8151/0', 'insulinoma, nos'),
('8151/3', 'insulinoma, malignant'),
('8152/1', 'glucagonoma, nos'),
('8152/3', 'glucagonoma, malignant'),
('8153/1', 'gastrinoma, nos'),
('8153/3', 'gastrinoma, malignant'),
('8154/3', 'mixed islet cell and exocrine adenocarcinoma'),
('8155/1', 'vipoma, nos'),
('8155/3', 'vipoma, malignant'),
('8156/1', 'somatostatinoma, nos'),
('8156/3', 'somatostatinoma, malignant'),
('8157/1', 'enteroglucagonoma, nos'),
('8157/3', 'enteroglucagonoma, malignant'),
('8160/0', 'bile duct adenoma'),
('8160/3', 'cholangiocarcinoma'),
('8161/0', 'bile duct cystadenoma'),
('8161/3', 'bile duct cystadenocarcinoma'),
('8162/3', 'klatskin tumor'),
('8170/0', 'liver cell adenoma'),
('8170/3', 'hepatocellular carcinoma, nos'),
('8171/3', 'hepatocellular carcinoma, fibrolamellar'),
('8172/3', 'hepatocellular carcinoma, scirrhous'),
('8173/3', 'hepatocellular carcinoma, spindle cell variant'),
('8174/3', 'hepatocellular carcinoma, clear cell type'),
('8175/3', 'hepatocellular carcinoma, pleomorphic type'),
('8180/3', 'combined hepatocellular carcinoma and cholangiocarcinoma'),
('8190/0', 'trabecular adenoma'),
('8190/3', 'trabecular adenocarcinoma'),
('8191/0', 'embryonal adenoma'),
('8200/0', 'eccrine dermal cylindroma'),
('8200/3', 'adenoid cystic carcinoma'),
('8201/2', 'cribriform carcinoma in situ'),
('8201/3', 'cribriform carcinoma, nos'),
('8202/0', 'microcystic adenoma'),
('8204/0', 'lactating adenoma'),
('8210/0', 'adenomatous polyp, nos'),
('8210/2', 'adenocarcinoma in situ in adenomatous polyp'),
('8210/3', 'adenocarcinoma in adenomatous polyp'),
('8211/0', 'tubular adenoma, nos'),
('8211/3', 'tubular adenocarcinoma'),
('8212/0', 'flat adenoma'),
('8213/0', 'serrated adenoma'),
('8214/3', 'parietal cell carcinoma'),
('8215/3', 'adenocarcinoma of anal glands'),
('8220/0', 'adenomatous polyposis coli'),
('8220/3', 'adenocarcinoma in adenomatous polyposis coli'),
('8221/0', 'multiple adenomatous polyps'),
('8221/3', 'adenocarcinoma in multiple adenomatous polyps'),
('8230/2', 'ductal carcinoma in situ, solid type'),
('8230/3', 'solid carcinoma, nos'),
('8231/3', 'carcinoma simplex'),
('8240/1', 'carcinoid tumor of uncertain malignant potential'),
('8240/3', 'carcinoid tumor, nos (except of appendix M-8240/1)'),
('8241/3', 'enterochromaffin cell carcinoid'),
('8242/1', 'enterochromaffin-like cell carcinoid, nos'),
('8242/3', 'enterochromaffin-like cell tumor, malignant'),
('8243/3', 'goblet cell carcinoid'),
('8244/3', 'composite carcinoid'),
('8245/1', 'tubular carcinoid'),
('8245/3', 'adenocarcinoid tumor'),
('8246/3', 'neuroendocrine carcinoma, nos'),
('8247/3', 'merkel cell carcinoma'),
('8248/1', 'apudoma'),
('8249/3', 'atypical carcinoid tumor'),
('8250/1', 'pulmonary adenomatosis'),
('8250/3', 'bronchiolo-alveolar adenocarcinoma, nos'),
('8251/0', 'alveolar adenoma'),
('8251/3', 'alveolar adenocarcinoma'),
('8252/3', 'bronchiolo-alveolar carcinoma, non-mucinous'),
('8253/3', 'bronchiolo-alveolar carcinoma, mucinous'),
('8254/3', 'bronchiolo-alveolar carcinoma, mixed mucinous and non-mucinous'),
('8255/3', 'adenocarcinoma with mixed subtypes'),
('8260/0', 'papillary adenoma, nos'),
('8260/3', 'papillary adenocarcinoma, nos'),
('8261/0', 'villous adenoma, nos'),
('8261/2', 'adenocarcinoma in situ in villous adenoma'),
('8261/3', 'adenocarcinoma in villous adenoma'),
('8262/3', 'villous adenocarcinoma'),
('8263/0', 'tubulovilous adenoma, nos'),
('8263/1', 'borderline carcinoma in situ in a tubulovillous adenoma'),
('8263/2', 'adenocarcinoma in situ in tubulovillous adenoma'),
('8263/3', 'adenocarcinoma in tubulovillous adenoma'),
('8264/0', 'papillomatosis, glandular'),
('8270/0', 'chromophobe adenoma'),
('8270/3', 'chromophobe carcinoma'),
('8271/0', 'prolactinoma'),
('8272/0', 'pituitary adenoma'),
('8272/3', 'pituitary carcinoma, nos'),
('8280/0', 'acidophil adenoma'),
('8280/3', 'acidophil carcinoma'),
('8281/0', 'mixed acidophil-basophil adenoma'),
('8281/3', 'mixed acidophil-basophil carcinoma'),
('8290/0', 'oxyphilic adenoma'),
('8290/3', 'oxyphilic adenocarcinoma'),
('8300/0', 'basophil adenoma'),
('8300/3', 'basophil carcinoma'),
('8310/0', 'clear cell adenoma'),
('8310/3', 'clear cell adenocarcinoma, nos'),
('8311/1', 'hypernephroid tumor [obs]'),
('8312/3', 'renal cell carcinoma, nos'),
('8313/0', 'clear cell adenofibroma'),
('8313/1', 'clear cell adenofibroma of borderline malignancy'),
('8313/3', 'clear cell adenocarcinofibroma'),
('8314/3', 'lipid-rich carcinoma'),
('8315/3', 'glycogen-rich carcinoma'),
('8316/3', 'cyst-associated renal cell carcinoma'),
('8317/3', 'renal cell carcinoma, chromophobe type'),
('8318/3', 'renal cell carcinoma, sarcomatoid'),
('8319/3', 'collecting duct carcinoma'),
('8320/3', 'granular cell carcinoma'),
('8321/0', 'chief cell adenoma'),
('8322/0', 'water-clear cell adenoma'),
('8322/3', 'water-clear cell adenocarcinoma'),
('8323/0', 'mixed cell adenoma'),
('8323/3', 'mixed cell adenocarcinoma'),
('8324/0', 'lipoadenoma'),
('8325/0', 'metanephric adenoma'),
('8330/0', 'follicular adenoma'),
('8330/1', 'atypical follicular adenoma'),
('8330/3', 'follicular adenocarcinoma, nos'),
('8331/3', 'follicular adenocarcinoma, well differentiated'),
('8332/3', 'follicular adenocarcinoma, trabecular'),
('8333/0', 'microfollicular adenoma, nos'),
('8333/3', 'fetal adenocarcinoma'),
('8334/0', 'macrofollicular adenoma'),
('8335/3', 'follicular carcinoma, minimally invasive'),
('8336/0', 'hyalinizing trabecular adenoma'),
('8337/3', 'insular carcinoma'),
('8340/3', 'papillary carcinoma, follicular variant'),
('8341/3', 'papillary microcarcinoma'),
('8342/3', 'papillary carcinoma, oxyphilic cell'),
('8343/3', 'papillary carcinoma, encapsulated'),
('8344/3', 'papillary carcinoma, columnar cell'),
('8345/3', 'medullary carcinoma with amyloid stroma'),
('8346/3', 'mixed medullary-follicular carcinoma'),
('8347/3', 'mixed medullary-papillary carcinoma'),
('8350/3', 'nonencapsulated sclerosing carcinoma'),
('8360/1', 'multiple endocrine adenomas'),
('8361/0', 'juxtaglomerular tumor'),
('8370/0', 'adrenal cortical adenoma, nos'),
('8370/3', 'adrenal cortical carcinoma'),
('8371/0', 'adrenal cortical adenoma, compact cell'),
('8372/0', 'adrenal cortical adenoma, pigmented'),
('8373/0', 'adrenal cortical adenoma, clear cell'),
('8374/0', 'adrenal cortical adenoma, glomerulosa cell'),
('8375/0', 'adrenal cortical adenoma, mixed cell'),
('8380/0', 'endometrioid adenoma, nos'),
('8380/1', 'endometrioid adenoma, borderline malignancy'),
('8380/3', 'endometrioid adenocarcinoma, nos'),
('8381/0', 'endometrioid adenofibroma, nos'),
('8381/1', 'endometrioid adenofibroma, borderline malignancy'),
('8381/3', 'endometrioid adenofibroma, malignant'),
('8382/3', 'endometrioid adenocarcinoma, secretory variant'),
('8383/3', 'endometrioid adenocarcinoma, ciliated cell variant'),
('8384/2', 'endocervical type adenocarcinoma in situ'),
('8384/3', 'adenocarcinoma, endocervical type'),
('8390/0', 'skin appendage adenoma'),
('8390/3', 'skin appendage carcinoma'),
('8391/0', 'follicular fibroma'),
('8392/0', 'syringofibroadenoma'),
('8400/0', 'sweat gland adenoma'),
('8400/1', 'sweat gland tumor, nos'),
('8400/3', 'sweat gland adenocarcinoma'),
('8401/0', 'apocrine adenoma'),
('8401/3', 'apocrine adenocarcinoma'),
('8402/0', 'nodular hidradenoma'),
('8402/3', 'nodular hidradenoma, malignant'),
('8403/0', 'eccrine spiradenoma'),
('8403/3', 'malignant eccrine spiradenoma'),
('8404/0', 'hidrocystoma'),
('8405/0', 'papillary hidradenoma'),
('8406/0', 'papillary syringadenoma'),
('8407/0', 'syringoma, nos'),
('8407/3', 'sclerosing sweat duct carcinoma'),
('8408/0', 'eccrine papillary adenoma'),
('8408/1', 'aggressive digital papillary adenoma'),
('8408/3', 'eccrine papillary adenocarcinoma'),
('8409/0', 'eccrine poroma'),
('8409/3', 'eccrine poroma, malignant'),
('8410/0', 'sebaceous adenoma'),
('8410/3', 'sebaceous adenocarcinoma'),
('8413/3', 'eccrine adenocarcinoma'),
('8420/0', 'ceruminous adenoma'),
('8420/3', 'ceruminous adenocarcinoma'),
('8430/1', 'mucoepidermoid tumor [obs]'),
('8430/3', 'mucoepidermoid carcinoma'),
('8440/0', 'cystadenoma, nos'),
('8440/3', 'cystadenocarcinoma, nos'),
('8441/0', 'serous cystadenoma, nos'),
('8441/3', 'serous cystadenocarcinoma, nos'),
('8442/1', 'serous cystadenoma, borderline malignancy'),
('8443/0', 'clear cell cystadenoma'),
('8444/1', 'clear cell cystic tumor of borderline malignancy'),
('8450/0', 'papillary cystadenoma, nos'),
('8450/3', 'papillary cystadenocarcinoma, nos'),
('8451/1', 'papillary cystadenoma, borderline malignancy'),
('8452/1', 'solid pseudopapillary tumor'),
('8452/3', 'solid pseudopapillary carcinoma'),
('8453/0', 'intraductal papillary-mucinous adenoma'),
('8453/1', 'intraductal papillary-mucinous tumor with moderate dysplasia'),
('8453/2', 'intraductal papillary-mucinous carcinoma, non-invasive'),
('8453/3', 'intraductal papillary-mucinous carcinoma, invasive'),
('8454/0', 'cystic tumor of atrio-ventricular node'),
('8460/0', 'papillary serous cystadenoma, nos'),
('8460/3', 'papillary serous cystadenocarcinoma'),
('8461/0', 'serous surface papilloma'),
('8461/3', 'serous surface papillary carcinoma'),
('8462/1', 'serous papillary cystic tumor of borderline malignancy'),
('8463/1', 'serous surface papillary tumor of borderline malignancy'),
('8470/0', 'mucinous cystadenoma, nos'),
('8470/1', 'mucinous cystic tumor with moderate dysplasia'),
('8470/2', 'mucinous cystadenocarcinoma, non-invasive'),
('8470/3', 'mucinous cystadenocarcinoma, nos'),
('8471/0', 'papillary mucinous cystadenoma, nos'),
('8471/3', 'papillary mucinous cystadenocarcinoma'),
('8472/1', 'mucinous cystic tumor of borderline malignancy'),
('8473/1', 'papillary mucinous cystadenoma, borderline malignancy'),
('8480/0', 'mucinous adenoma'),
('8480/2', 'mucinous adenocarcinoma in situ'),
('8480/3', 'mucinous adenocarcinoma'),
('8480/6', 'pseudomyxoma peritonei'),
('8481/3', 'mucin-producing adenocarcinoma'),
('8482/3', 'mucinous adenocarcinoma, endocervical type'),
('8490/3', 'signet ring cell carcinoma'),
('8490/6', 'metastatic signet ring cell carcinoma'),
('8500/2', 'intraductal carcinoma, noninfiltrating, nos'),
('8500/3', 'infiltrating duct carcinoma, nos'),
('8501/2', 'comedocarcinoma, noninfiltrating'),
('8501/3', 'comedocarcinoma, nos'),
('8502/3', 'secretory carcinoma of breast'),
('8503/0', 'intraductal papilloma'),
('8503/2', 'noninfiltrating intraductal papillary adenocarcinoma'),
('8503/3', 'intraductal papillary adenocarcinoma with invasion'),
('8504/0', 'intracystic papillary adenoma'),
('8504/2', 'noninfiltrating intracystic carcinoma'),
('8504/3', 'intracystic carcinoma, nos'),
('8505/0', 'intraductal papillomatosis, nos'),
('8506/0', 'adenoma of nipple'),
('8507/1', 'intraductal micropapillary carcinoma borderline'),
('8507/2', 'intraductal micropapillary carcinoma'),
('8507/3', 'invasive micropapillary carcinoma'),
('8508/3', 'cystic hypersecretory carcinoma'),
('8510/3', 'medullary carcinoma, nos'),
('8512/3', 'medullary carcinoma with lymphoid stroma'),
('8513/3', 'atypical medullary carcinoma'),
('8514/3', 'duct carcinoma, desmoplastic type'),
('8520/1', 'lobular neoplasia borderline'),
('8520/2', 'lobular carcinoma in situ, nos'),
('8520/3', 'lobular carcinoma, nos'),
('8521/3', 'infiltrating ductular carcinoma'),
('8522/2', 'intraductal carcinoma and lobular carcinoma in situ'),
('8522/3', 'infiltrating duct and lobular carcinoma'),
('8523/2', 'intraductal carcinoma mixed with other types of in situ carcinoma'),
('8523/3', 'infiltrating duct mixed with other types of carcinoma'),
('8524/3', 'infiltrating lobular mixed with other types of carcinoma'),
('8525/3', 'polymorphous low grade adenocarcinoma'),
('8530/3', 'inflammatory carcinoma'),
('8540/3', 'paget disease, mammary'),
('8541/3', 'paget disease and infiltrating duct carcinoma of breast'),
('8542/3', 'paget disease, extramammary (except paget disease of bone)'),
('8543/3', 'paget disease and intraductal carcinoma of breast'),
('8550/0', 'acinar cell adenoma'),
('8550/1', 'acinar cell tumor [obs]'),
('8550/3', 'acinar cell carcinoma'),
('8551/3', 'acinar cell cystadenocarcinoma'),
('8560/0', 'mixed squamous cell and glandular papilloma'),
('8560/2', 'adenosquamous carcinoma in situ'),
('8560/3', 'adenosquamous carcinoma'),
('8561/0', 'adenolymphoma'),
('8562/3', 'epithelial-myoepithelial carcinoma'),
('8570/3', 'adenocarcinoma with squamous metaplasia'),
('8571/3', 'adenocarcinoma with cartilaginous and osseous metaplasia'),
('8572/3', 'adenocarcinoma with spindle cell metaplasia'),
('8573/3', 'adenocarcinoma with apocrine metaplasia'),
('8574/3', 'adenocarcinoma with neuroendocrine differentiation'),
('8575/3', 'metaplastic carcinoma, nos'),
('8576/3', 'hepatoid adenocarcinoma'),
('8580/0', 'thymoma, benign'),
('8580/1', 'thymoma, nos'),
('8580/3', 'thymoma, malignant, nos'),
('8581/1', 'thymoma, type A, nos'),
('8581/3', 'thymoma, type A, malignant'),
('8582/1', 'thymoma, type AB, nos'),
('8582/3', 'thymoma, type AB, malignant'),
('8583/1', 'thymoma, type B1, nos'),
('8583/3', 'thymoma, type B1, malignant'),
('8584/1', 'thymoma, type B2, nos'),
('8584/3', 'thymoma, type B2, malignant'),
('8585/1', 'thymoma, type B3, nos'),
('8585/3', 'thymoma, type B3, malignant'),
('8586/3', 'thymic carcinoma, nos'),
('8587/0', 'ectopic hamartomatous thymoma'),
('8588/3', 'spindle epithelial tumor with thymus-like element'),
('8589/3', 'carcinoma showing thymus-like element'),
('8590/1', 'sex cord-gonadal stromal tumor, nos'),
('8591/1', 'sex cord-gonadal stromal tumor, incompletely differentiated'),
('8592/1', 'sex cord-gonadal stromal tumor, mixed forms'),
('8593/1', 'stromal tumor with minor sex cord elements'),
('8600/0', 'thecoma, nos'),
('8600/3', 'thecoma, malignant'),
('8601/0', 'thecoma, luteinized'),
('8602/0', 'sclerosing stromal tumor'),
('8610/0', 'luteoma, nos'),
('8620/1', 'granulosa cell tumor, adult type'),
('8620/3', 'granulosa cell tumor, malignant'),
('8621/1', 'granulosa cell-theca cell tumor'),
('8622/1', 'granulosa cell tumor, juvenile'),
('8623/1', 'sex cord tumor with annular tubules'),
('8630/0', 'androblastoma, benign'),
('8630/1', 'androblastoma, nos'),
('8630/3', 'androblastoma, malignant'),
('8631/0', 'sertoli-leydig cell tumor, well differentiated'),
('8631/1', 'sertoli-leydig cell tumor of intermediate differentiation'),
('8631/3', 'sertoli-leydig cell tumor, poorly differentiated'),
('8632/1', 'gynandroblastoma'),
('8633/1', 'sertoli-leydig cell tumor, retiform'),
('8634/1', 'sertoli-leydig cell tumor, intermediate differentiation, with heterologous elements'),
('8634/3', 'sertoli-leydig cell tumor, poorly differentiated, with heterologous elements'),
('8640/1', 'sertoli cell tumor, nos'),
('8640/3', 'sertoli cell carcinoma'),
('8641/0', 'sertoli cell tumor with lipid storage'),
('8642/1', 'large cell calcifying sertoli cell tumor'),
('8650/0', 'leydig cell tumor, benign'),
('8650/1', 'leydig cell tumor, nos'),
('8650/3', 'leydig cell tumor, malignant'),
('8660/0', 'hilus cell tumor'),
('8670/0', 'lipid cell tumor of ovary'),
('8670/3', 'steroid cell tumor, malignant'),
('8671/0', 'adrenal rest tumor'),
('8680/0', 'paraganglioma, benign'),
('8680/1', 'paraganglioma, nos'),
('8680/3', 'paraganglioma, malignant'),
('8681/1', 'sympathetic paraganglioma'),
('8682/1', 'parasympathetic paraganglioma'),
('8683/0', 'gangliocytic paraganglioma'),
('8690/1', 'glomus jugulare tumor, nos'),
('8691/1', 'aortic body tumor'),
('8692/1', 'carotid body tumor'),
('8693/1', 'extra-adrenal paraganglioma, nos'),
('8693/3', 'extra-adrenal paraganglioma, malignant'),
('8700/0', 'pheochromocytoma, nos'),
('8700/3', 'pheochromocytoma, malignant'),
('8710/3', 'glomangiosarcoma'),
('8711/0', 'glomus tumor, nos'),
('8711/3', 'glomus tumor, malignant'),
('8712/0', 'glomangioma'),
('8713/0', 'glomangiomyoma'),
('8720/0', 'pigmented nevus, nos'),
('8720/1', 'melanoma of uncertain malignant potential'),
('8720/2', 'melanoma in situ'),
('8720/3', 'malignant melanoma, nos (except juvenile melanoma M-8770/0)'),
('8721/3', 'nodular melanoma'),
('8722/0', 'balloon cell nevus'),
('8722/3', 'balloon cell melanoma'),
('8723/0', 'halo nevus'),
('8723/3', 'malignant melanoma, regressing'),
('8725/0', 'neuronevus'),
('8726/0', 'magnocellular nevus'),
('8727/0', 'dysplastic nevus'),
('8728/0', 'diffuse melanocytosis'),
('8728/1', 'meningeal melanocytoma'),
('8728/3', 'meningeal melanomatosis'),
('8730/0', 'nonpigmented nevus'),
('8730/3', 'amelanotic melanoma'),
('8740/0', 'junctional nevus'),
('8740/3', 'malignant melanoma in junctional nevus'),
('8741/2', 'precancerous melanosis, nos'),
('8741/3', 'malignant melanoma in precancerous melanosis'),
('8742/2', 'lentigo maligna'),
('8742/3', 'lentigo malgna melanoma'),
('8743/2', 'superficial spreading melanoma in situ'),
('8743/3', 'superficial spreading melanoma'),
('8744/1', 'acral lentiginous melanoma, uncertain malignant potential'),
('8744/3', 'acral lentiginous melanoma, malignant'),
('8745/3', 'desmoplastic melanoma, malignant'),
('8746/2', 'lentiginous melanoma in situ, mucosal'),
('8746/3', 'mucosal lentiginous melanoma'),
('8750/0', 'intradermal nevus'),
('8760/0', 'compound nevus'),
('8761/0', 'small congenital nevus'),
('8761/1', 'giant pigmented nevus, nos'),
('8761/3', 'malignant melanoma in giant pigmented nevus'),
('8762/1', 'proliferative dermal lesion in congenital nevus'),
('8770/0', 'epitheliod and spindle cell nevus'),
('8770/3', 'mixed epitheliod and spindle cell melanoma'),
('8771/0', 'epitheliod cell nevus'),
('8771/3', 'epitheliod cell melanoma'),
('8772/0', 'spindle cell nevus, nos'),
('8772/3', 'spindle cell melanoma, nos'),
('8773/3', 'spindle cell melanoma, type A'),
('8774/3', 'spindle cell melanoma, type B'),
('8780/0', 'blue nevus, nos'),
('8780/3', 'blue nevus, malignant'),
('8790/0', 'cellular blue nevus'),
('8800/0', 'soft tissue tumor, benign'),
('8800/3', 'sarcoma, nos'),
('8800/9', 'sarcomatosis, nos'),
('8801/3', 'spindle cell sarcoma'),
('8802/3', 'giant cell sarcoma (except of bone M-9250/3)'),
('8803/3', 'small cell sarcoma'),
('8804/3', 'epitheliod sarcoma'),
('8805/3', 'undifferentiated sarcoma'),
('8806/3', 'desmoplastic small round cell tumor'),
('8810/0', 'fibroma, nos'),
('8810/1', 'cellular fibroma'),
('8810/3', 'fibrosarcoma'),
('8811/0', 'fibromyxoma'),
('8811/3', 'fibromyxosarcoma'),
('8812/0', 'periosteal fibroma'),
('8812/3', 'periosteal fibrosarcoma'),
('8813/0', 'fascial fibroma'),
('8813/3', 'fascial fibrosarcoma'),
('8814/3', 'infantile fibrosarcoma'),
('8815/0', 'solitary fibrous tumor'),
('8815/3', 'solitary fibrous tumor, malignant'),
('8820/0', 'elastofibroma'),
('8821/1', 'aggressive fibromatosis'),
('8822/1', 'abdominal fibromatosis'),
('8823/0', 'desmoplastic fibroma'),
('8824/0', 'myofibroma'),
('8824/1', 'myofibromatosis'),
('8825/0', 'myofibroblastoma'),
('8825/1', 'myofibroblastic tumor, nos'),
('8825/3', 'myofibroblastic sarcoma'),
('8826/0', 'angiomyofibroblastoma'),
('8827/1', 'myofibroblastic tumor, peribronchial'),
('8830/0', 'benign fibrous histiocytoma'),
('8830/1', 'atypical fibrous histiocytoma'),
('8830/3', 'malignant fibrous histiocytoma'),
('8831/0', 'histiocytoma, nos'),
('8832/0', 'dermatofibroma, nos'),
('8832/3', 'dermatofibrosarcoma,nos'),
('8833/3', 'pigmented dermatofibrosarcoma protuberans'),
('8834/1', 'giant cell fibroblastoma'),
('8835/1', 'plexiform fibrohistiocytic tumor'),
('8836/1', 'angiomatoid fibrous histiocytoma'),
('8840/0', 'myxoma, nos'),
('8840/3', 'myxosarcoma'),
('8841/1', 'angiomyxoma'),
('8842/0', 'ossifying fibromyxoid tumor'),
('8850/0', 'lipoma, nos'),
('8850/1', 'atypical lipoma'),
('8850/3', 'liposarcoma, nos'),
('8851/0', 'fibrolipoma'),
('8851/3', 'liposarcoma, well differentiated'),
('8852/0', 'fibromyxolipoma'),
('8852/3', 'myxoid liposarcoma'),
('8853/3', 'round cell liposarcoma'),
('8854/0', 'pleomorphic lipoma'),
('8854/3', 'pleomorphic liposarcoma'),
('8855/3', 'mixed liposarcoma'),
('8856/0', 'intramuscular lipoma'),
('8857/0', 'spindle cell lipoma'),
('8857/3', 'fibroblastic liposarcoma'),
('8858/3', 'dedifferentiated liposarcoma'),
('8860/0', 'angiomyolipoma'),
('8861/0', 'angiolipoma, nos'),
('8862/0', 'chondroid lipoma'),
('8870/0', 'myelolipoma'),
('8880/0', 'hibernoma'),
('8881/0', 'lipoblastomatosis'),
('8890/0', 'leiomyoma, nos'),
('8890/1', 'leiomyomatosis, nos'),
('8890/3', 'leiomyosarcoma, nos'),
('8891/0', 'epitheliod leiomyoma'),
('8891/3', 'epitheliod leiomyosarcoma'),
('8892/0', 'cellular leiomyoma'),
('8893/0', 'bizzare leiomyoma'),
('8894/0', 'angiomyoma'),
('8894/3', 'angiomyosarcoma'),
('8895/0', 'myoma'),
('8895/3', 'myosarcoma'),
('8896/3', 'myxoid leiomyosarcoma'),
('8897/1', 'smooth muscle tumor of uncertain malignant potential'),
('8898/1', 'metastasizing leiomyoma'),
('8900/0', 'rhabdomyoma, nos'),
('8900/3', 'rhabdomyosarcoma, nos'),
('8901/3', 'pleomorphic rhabdomyosarcoma, adult type'),
('8902/3', 'mixed type rhabdomyosarcoma'),
('8903/0', 'fetal rhabdomyoma'),
('8904/0', 'adult rhabdomyoma'),
('8905/0', 'genital rhabdomyoma'),
('8910/3', 'embryonal rhabdomyosarcoma, nos'),
('8912/3', 'spindle cell rhabdomyosarcoma'),
('8920/3', 'alveolar rhabdomyosarcoma'),
('8921/3', 'rhabdomyosarcoma with ganglionic differentiation'),
('8930/0', 'endometrial stromal nodule'),
('8930/3', 'endometrial stromal sarcoma, nos'),
('8931/3', 'endometrial stromal sarcoma, low grade'),
('8932/0', 'adenomyoma'),
('8933/3', 'adenosarcoma'),
('8934/3', 'carcinofibroma'),
('8935/0', 'stromal tumor, benign'),
('8935/1', 'stromal tumor, nos'),
('8935/3', 'stromal sarcoma, nos'),
('8936/0', 'gastrointestinal stromal tumor, benign'),
('8936/1', 'gastrointestinal stromal tumor, nos'),
('8936/3', 'gastrointestinal stromal sarcoma'),
('8940/0', 'pleomorphic adenoma'),
('8940/3', 'mixed tumor, malignant, nos'),
('8941/3', 'carcinoma in pleomorphic adenoma'),
('8950/1', 'mixed mullerian tumour of borderline malignancy'),
('8950/3', 'mullerian mixed tumor'),
('8951/3', 'mesodermal mixed tumor'),
('8959/0', 'benign cystic nephroma'),
('8959/1', 'cystic partially differentiated nephroblastoma'),
('8959/3', 'malignant cystic nephroma'),
('8960/1', 'mesoblastic nephroma'),
('8960/3', 'nephroblastoma, nos'),
('8963/3', 'malignant rhabdoid tumor'),
('8964/3', 'clear cell sarcoma of kidney'),
('8965/0', 'nephrogenic adenofibroma'),
('8966/0', 'renomedullary interstitial cell tumor'),
('8967/0', 'ossifying renal tumor'),
('8970/3', 'hepatoblastoma'),
('8971/3', 'pancreatoblastoma'),
('8972/3', 'pulmonary blastoma'),
('8973/3', 'pleuropulmonary blastoma'),
('8974/1', 'sialoblastoma'),
('8980/3', 'carcinosarcoma, nos'),
('8981/3', 'carcinosarcoma, embryonal'),
('8982/0', 'myoepithelioma'),
('8982/3', 'malignant myoepithelioma'),
('8983/0', 'adenomyoepithelioma'),
('8990/0', 'mesenchymoma, benign'),
('8990/1', 'mesenchymoma, nos'),
('8990/3', 'mesenchymoma, malignant'),
('8991/3', 'embryonal sarcoma'),
('9000/0', 'brenner tumor, nos'),
('9000/1', 'brenner tumor, borderline malignancy'),
('9000/3', 'brenner tumor, malignant'),
('9010/0', 'fibroadenoma, nos'),
('9011/0', 'intracanalicular fibroadenoma'),
('9012/0', 'pericanalicular fibroadenoma'),
('9013/0', 'adenofibroma, nos'),
('9014/0', 'serous adenofibroma, nos'),
('9014/1', 'serous adenofibroma of borderline malignancy'),
('9014/3', 'serous adenocarcinofibroma'),
('9015/0', 'mucinous adenofibroma, nos'),
('9015/1', 'mucinous adenofibroma of borderline malignancy'),
('9015/3', 'mucinous adenocarcinofibroma'),
('9016/0', 'giant fibroadenoma'),
('9020/0', 'phyllodes tumor, benign'),
('9020/1', 'phyllodes tumor, borderline'),
('9020/3', 'phyllodes tumor, malignant'),
('9030/0', 'juvenile fibroadenoma'),
('9040/0', 'synovioma, benign'),
('9040/3', 'synovial sarcoma, nos'),
('9041/3', 'synovial sarcoma, spindle cell'),
('9042/3', 'synovial sarcoma, epithelioid cell'),
('9043/3', 'synovial sarcoma, biphasic'),
('9044/3', 'clear cell sarcoma, nos (except of kidney M-8964/3)'),
('9050/0', 'mesothelioma, benign'),
('9050/3', 'mesothelioma, malignant'),
('9051/0', 'fibrous mesothelioma, benign'),
('9051/3', 'fibrous mesothelioma, malignant'),
('9052/0', 'epithelioid mesothelioma, benign'),
('9052/3', 'epithelioid mesothelioma, malignant'),
('9053/3', 'mesothelioma, biphasic, malignant'),
('9054/0', 'adenomatoid tumor, nos'),
('9055/0', 'multicystic mesothelioma, benign'),
('9055/1', 'cystic mesothelioma, nos'),
('9060/3', 'dysgerminoma'),
('9061/3', 'seminoma, nos'),
('9062/3', 'seminoma, anaplastic'),
('9063/3', 'spermatocytic seminoma'),
('9064/2', 'intratubular malignant germ cells'),
('9064/3', 'germinoma'),
('9065/3', 'germ cell tumor, nonseminomatous'),
('9070/3', 'embryonal carcinoma, nos'),
('9071/3', 'yolk sac tumor'),
('9072/3', 'polyembryoma'),
('9073/1', 'gonadoblastoma'),
('9080/0', 'teratoma, benign'),
('9080/1', 'teratoma, nos'),
('9080/3', 'teratoma, malignant, nos'),
('9081/3', 'teratocarcinoma'),
('9082/3', 'malignant teratoma, undifferentiated'),
('9083/3', 'malignant teratoma, intermediate'),
('9084/0', 'dermoid cyst, nos'),
('9084/3', 'teratoma with malignant transformation'),
('9085/3', 'mixed germ cell tumor'),
('9090/0', 'struma ovarii, nos'),
('9090/3', 'struma ovarii, malignant'),
('9091/1', 'strumal carcinoid'),
('9100/0', 'hydatidiform mole, nos'),
('9100/1', 'invasive hydatidiform mole'),
('9100/3', 'choriocarcinoma, nos'),
('9101/3', 'choriocarcinoma combined with other germ cell elements'),
('9102/3', 'malignant teratoma, trophoblastic'),
('9103/0', 'partial hydatidiform mole'),
('9104/1', 'placental site trophoblastic tumor'),
('9105/3', 'trophoblastic tumor, epithelioid'),
('9110/0', 'mesonephroma, benign'),
('9110/1', 'mesonephric tumor, nos'),
('9110/3', 'mesonephroma, malignant'),
('9120/0', 'hemangioma, nos'),
('9120/3', 'hemangiosarcoma'),
('9121/0', 'cavernous hemangioma'),
('9122/0', 'venous hemangioma'),
('9123/0', 'racemose hemangioma'),
('9124/3', 'kupffer cell sarcoma'),
('9125/0', 'epithelioid hemangioma'),
('9130/0', 'hemangioendothelioma, benign'),
('9130/1', 'hemangioendothelioma, nos'),
('9130/3', 'hemangioendothelioma, malignant'),
('9131/0', 'capillary hemangioma'),
('9132/0', 'intramuscular hemangioma'),
('9133/1', 'epithelioid hemangioendothelioma, nos'),
('9133/3', 'epitheliod hemangioendothelioma, malignant'),
('9135/1', 'endovascular papillary angioendothelioma'),
('9136/1', 'spindle cell hemangioendothelioma'),
('9140/3', 'kaposi sarcoma'),
('9141/0', 'angiokeratoma'),
('9142/0', 'verrucous keratotic hemangioma'),
('9150/0', 'hemangiopericytoma, benign'),
('9150/1', 'hemangiopericytoma, nos'),
('9150/3', 'hemangiopericytoma, malignant'),
('9160/0', 'angiofibroma, nos'),
('9161/0', 'acquired tufted hemangioma'),
('9161/1', 'hemangioblastoma'),
('9170/0', 'lymphangioma, nos'),
('9170/3', 'lymphangiosarcoma'),
('9171/0', 'capillary lymphangioma'),
('9172/0', 'cavernous lymphangioma'),
('9173/0', 'cystic lymphangioma'),
('9174/0', 'lymphangiomyoma'),
('9174/1', 'lymphangiomyomatosis'),
('9175/0', 'hemolymphangioma'),
('9180/0', 'osteoma, nos'),
('9180/3', 'osteosarcoma, nos'),
('9181/3', 'chondroblastic osteosarcoma'),
('9182/3', 'fibroblastic osteosarcoma'),
('9183/3', 'telangiectatic osteosarcoma'),
('9184/3', 'osteosarcoma in paget disease of bone'),
('9185/3', 'small cell osteosarcoma'),
('9186/3', 'central osteosarcoma'),
('9187/3', 'intraosseous well differentiated osteosarcoma'),
('9191/0', 'osteoid osteoma, nos'),
('9192/3', 'parosteal osteosarcoma'),
('9193/3', 'periosteal osteosarcoma'),
('9194/3', 'high grade surface osteosarcoma'),
('9195/3', 'intracortical osteosarcoma'),
('9200/0', 'osteoblastoma, nos'),
('9200/1', 'aggressive osteoblastoma'),
('9210/0', 'osteochondroma'),
('9210/1', 'osteochondromatosis, nos'),
('9220/0', 'chondroma, nos'),
('9220/1', 'chondromatosis, nos'),
('9220/3', 'chondrosarcoma, nos'),
('9221/0', 'juxtacortical chondroma'),
('9221/3', 'juxtacortical chondrosarcoma'),
('9230/0', 'chondroblastoma, nos'),
('9230/3', 'chondroblastoma, malignant'),
('9231/3', 'myxoid chondrosarcoma'),
('9240/3', 'mesenchymal chondrosarcoma'),
('9241/0', 'chondromyxoid fibroma'),
('9242/3', 'clear cell chondrosarcoma'),
('9243/3', 'dedifferentiated chondrosarcoma'),
('9250/1', 'giant cell tumor of bone, nos'),
('9250/3', 'giant cell tumor of bone, malignant'),
('9251/1', 'giant cell tumor of soft parts, nos'),
('9251/3', 'malignant giant cell tumor of soft parts'),
('9252/0', 'tenosynovial giant cell tumor'),
('9252/3', 'malignant tenosynovial giant cell tumor'),
('9260/3', 'ewing sarcoma'),
('9261/3', 'adamantinoma of long bones'),
('9262/0', 'ossifying fibroma'),
('9270/0', 'odontogenic tumor, benign'),
('9270/1', 'odontogenic tumor, nos'),
('9270/3', 'odontogenic tumor, malignant'),
('9271/0', 'ameloblastic fibrodentinoma'),
('9272/0', 'cementoma, nos'),
('9273/0', 'cementoblastoma, benign'),
('9274/0', 'cementifying fibroma'),
('9275/0', 'gigantiform cementoma'),
('9280/0', 'odontoma, nos'),
('9281/0', 'compound odontoma'),
('9282/0', 'complex odontoma'),
('9290/0', 'ameloblastic fibro-odontoma'),
('9290/3', 'ameloblastic odontosarcoma'),
('9300/0', 'adenomatoid odontogenic tumor'),
('9301/0', 'calcifying odontogenic cyst'),
('9302/0', 'odontogenic ghost cell tumor'),
('9310/0', 'ameloblastoma, nos'),
('9310/3', 'ameloblastoma, malignant'),
('9311/0', 'odontoameloblastoma'),
('9312/0', 'squamous odontogenic tumor'),
('9320/0', 'odontogenic myxoma'),
('9321/0', 'central odontogenic fibroma'),
('9322/0', 'peripheral odontogenic fibroma'),
('9330/0', 'ameloblastic fibroma'),
('9330/3', 'ameloblastic fibrosarcoma'),
('9340/0', 'calcifying epithelial odontogenic tumor'),
('9341/1', 'clear cell odontogenic tumor'),
('9342/3', 'odontogenic carcinosarcoma'),
('9350/1', 'craniopharyngioma'),
('9351/1', 'craniopharyngioma, adamantinomatous'),
('9352/1', 'craniopharyngioma, papillary'),
('9360/1', 'pinealoma'),
('9361/1', 'pineocytoma'),
('9362/3', 'pineoblastoma'),
('9363/0', 'melanotic neuroectodermal tumor'),
('9364/3', 'peripheral neuroectodermal tumor'),
('9365/3', 'askin tumor'),
('9370/3', 'chordoma, nos'),
('9371/3', 'chondroid chordoma'),
('9372/3', 'dedifferentiated chordoma'),
('9373/0', 'parachordoma'),
('9380/3', 'glioma, malignant'),
('9381/3', 'gliomatosis cerebri'),
('9382/3', 'mixed glioma'),
('9383/1', 'subependymoma'),
('9384/1', 'subependymal giant cell astrocytoma'),
('9390/0', 'choroid plexus papilloma, nos'),
('9390/1', 'atypical choroid plexus papilloma'),
('9390/3', 'choroid plexus carcinoma'),
('9391/3', 'ependymoma, nos'),
('9392/3', 'ependymoma, anaplastic'),
('9393/3', 'papillary ependymoma'),
('9394/1', 'myxopapillary ependymoma'),
('9400/3', 'astrocytoma, nos'),
('9401/3', 'astroyctoma, anaplastic'),
('9410/3', 'protoplasmic astrocytoma'),
('9411/3', 'gemistocytic astrocytoma'),
('9412/1', 'desmoplastic infantile astrocytoma'),
('9413/0', 'dysembryoplastic neuroepithelial tumor'),
('9420/3', 'fibrillary astrocytoma'),
('9421/3', 'pilocytic astrocytoma'),
('9423/3', 'polar spongioblastoma'),
('9424/3', 'pleomorphic xanthoastrocytoma'),
('9430/3', 'astroblastoma'),
('9440/3', 'glioblastoma, nos'),
('9441/3', 'giant cell glioblastoma'),
('9442/1', 'gliofibroma'),
('9442/3', 'gliosarcoma'),
('9444/1', 'chordoid glioma'),
('9450/3', 'oligodendroglioma, nos'),
('9451/3', 'oligodendroglioma, anaplastic'),
('9460/3', 'oligodendroblastoma [obs]'),
('9470/3', 'medulloblastoma, nos'),
('9471/3', 'desmoplastic nodular medulloblastoma'),
('9472/3', 'medullomyoblastoma'),
('9473/3', 'primitive neuroectodermal tumor, nos'),
('9474/3', 'large cell medulloblastoma'),
('9480/3', 'cerebellar sarcoma, nos [obs]'),
('9490/0', 'ganglioneuroma'),
('9490/3', 'ganglioneuroblastoma'),
('9491/0', 'ganglioneuromatosis'),
('9492/0', 'gangliocytoma'),
('9493/0', 'dysplastic gangliocytoma of cerebellum (lhermitte-duclos)'),
('9500/3', 'neuroblastoma, nos'),
('9501/0', 'medulloepithelioma, benign'),
('9501/3', 'medulloepithelioma, nos'),
('9502/0', 'teratoid medulloepithelioma, benign'),
('9502/3', 'teratoid medulloepithelioma'),
('9503/3', 'neuroepithelioma, nos'),
('9504/3', 'spongioneuroblastoma'),
('9505/1', 'ganglioglioma, nos'),
('9505/3', 'ganglioglioma, anaplastic'),
('9506/1', 'central neurocytoma'),
('9507/0', 'pacinian tumor'),
('9508/3', 'atypical teratoid/rhabdoid tumor'),
('9510/0', 'retinocytoma'),
('9510/3', 'retinoblastoma, nos'),
('9511/3', 'retinoblastoma, differentiated'),
('9512/3', 'retinoblastoma, undifferentiated'),
('9513/3', 'retinoblastoma, diffuse'),
('9514/1', 'retinoblastoma, spontaneously regressed'),
('9520/3', 'olfactory neurogenic tumor'),
('9521/3', 'olfactory neurocytoma'),
('9522/3', 'olfactory neuroblastoma'),
('9523/3', 'olfactory neuroepithelioma'),
('9530/0', 'meningioma, nos'),
('9530/1', 'meningiomatosis, nos'),
('9530/3', 'meningioma, malignant'),
('9531/0', 'meningothelial meningioma'),
('9532/0', 'fibrous meningioma'),
('9533/0', 'psammomatous meningioma'),
('9534/0', 'angiomatous meningioma'),
('9535/0', 'hemangioblastic meningioma [obs]'),
('9537/0', 'transitional meningioma'),
('9538/1', 'clear cell meningioma'),
('9538/3', 'papillary meningioma'),
('9539/1', 'atypical meningioma'),
('9539/3', 'menigeal sarcomatosis'),
('9540/0', 'neurofibroma, nos'),
('9540/1', 'neurofibromatosis, nos'),
('9540/3', 'malignant peripheral nerve sheath tumor'),
('9541/0', 'melanotic neurofibroma'),
('9550/0', 'plexiform neurofibroma'),
('9560/0', 'neurilemoma, nos'),
('9560/1', 'neurinomatosis'),
('9560/3', 'neurilemoma, malignant [obs]'),
('9561/3', 'malignant peripheral nerve sheath tumor with rhabdomyoblastic differentiation'),
('9562/0', 'neurothekeoma'),
('9570/0', 'neuroma, nos'),
('9571/0', 'perineurioma, nos'),
('9571/3', 'perineurioma, malignant'),
('9580/0', 'granular cell tumor, nos'),
('9580/3', 'granular cell tumor, malignant'),
('9581/3', 'alveolar soft part sarcoma'),
('9582/0', 'granular cell tumor of the sellar region'),
('9590/3', 'malignant lymphoma, nos'),
('9591/3', 'malignant lymphoma, non-hodgkin, nos'),
('9596/3', 'composite hodgkin and non-hodgkin lymphoma'),
('9650/3', 'hodgkin lymphoma, nos'),
('9651/3', 'hodgkin lymphoma, lymphocyte-rich'),
('9652/3', 'hodgkin lymphoma, mixed cellularity, nos'),
('9653/3', 'hodgkin lymphoma, lymphocyte depletion, nos'),
('9654/3', 'hodgkin lymphoma, lymphocyte depletion, diffuse fibrous'),
('9655/3', 'hodgkin lymphoma, lymphocyte depletion, reticular'),
('9659/3', 'hodgkin lymphoma, nodule lymphocyte predominance'),
('9661/3', 'hodgkin granuloma [obs]'),
('9662/3', 'hodgkin sarcoma [obs]'),
('9663/3', 'hodgkin lymphoma, nodular sclerosis, nos'),
('9664/3', 'hodgkin lymphoma, nodular sclerosis, cellular phase'),
('9665/3', 'hodgkin lymphoma, nodular sclerosis, grade 1'),
('9667/3', 'hodgkin lymphoma, nodular sclerosis, grade 2'),
('9670/3', 'malignant lymphoma, small B lymphocytic, nos (see also M-9823/3)'),
('9671/3', 'malignant lymphoma, lymphoplasmacytic (see also M-9761/3)'),
('9673/3', 'mantle cell lymphoma, includes all variants: blastic, pleomorphic, small cell'),
('9675/3', 'malignant lymphoma, mixed small and large cell, diffuse [obs] (see also M-9690/3)'),
('9678/3', 'primary effusion lymphoma'),
('9679/3', 'mediastinal large B-cell lymphoma'),
('9680/3', 'malignant lymphoma, large B-cell, diffuse, nos'),
('9684/3', 'malignant lymphoma, large B-cell, diffuse, immunoblastic, nos'),
('9687/3', 'burkitt lymphoma, nos (see also M-9826/3)'),
('9689/3', 'splenic marginal zone B-cell lymphoma'),
('9690/3', 'follicular lymphoma, nos (see also M-9675/3)'),
('9691/3', 'follicular lymphoma, grade 2'),
('9695/3', 'follicular lymphoma, grade 1'),
('9698/3', 'follicular lymphoma, grade 3'),
('9699/3', 'marginal zone B-cell lymphoma, nos'),
('9700/3', 'mycosis fungoides'),
('9701/3', 'sezary syndrome'),
('9702/3', 'mature T-cell lymphoma, nos'),
('9705/3', 'angioimmunoblastic T-cell lymphoma'),
('9708/3', 'subcutaneous panniculitis-like T-cell lymphoma'),
('9709/3', 'cutaneous T-cell lymphoma, nos'),
('9714/3', 'anaplastic large cell lymphoma, T cell and null cell type'),
('9716/3', 'hepatosplenic yo (gamma-delta) cell lymphoma'),
('9717/3', 'intestinal T-cell lymphoma'),
('9718/3', 'primary cutaneous CD30+ T-cell lymphoproliferative disorder'),
('9719/3', 'NK/T-cell lymphoma, nasal and nasal-type'),
('9727/3', 'precursor cell lymphoblastic lymphoma, nos (see also M-9835/3)'),
('9728/3', 'precursor B-cell lymphoblastic lymphoma (see also M-9836/3)'),
('9729/3', 'percursor T-cell lymphoblastic lymphoma (see also M-9837/3)'),
('9731/3', 'plasmacytoma, nos'),
('9732/3', 'multiple myeloma'),
('9733/3', 'plasma cell leukemia'),
('9734/3', 'plasmacytoma, extramedullary (not occurring in bone)'),
('9740/1', 'mastocytoma, nos'),
('9740/3', 'mast cell sarcoma'),
('9741/3', 'malignant mastocytosis'),
('9742/3', 'mast cell leukemia'),
('9750/3', 'malignant histiocytosis'),
('9751/1', 'langerhans cell histiocytosis, nos'),
('9752/1', 'langerhans cell histiocytosis, unifocal'),
('9753/1', 'langerhans cell histiocytosis, multifocal'),
('9754/3', 'langerhans cell histiocytosis, disseminated'),
('9755/3', 'histiocytic sarcoma'),
('9756/3', 'langerhans cell sarcoma'),
('9757/3', 'interdigitating dendritic cell sarcoma'),
('9758/3', 'follicular dendritic cell sarcoma'),
('9760/3', 'immunoproliferative disease, nos'),
('9761/3', 'waldenstrom macroglobulinemia (see also M-9671/3)'),
('9762/3', 'heavy chain disease, nos'),
('9764/3', 'immunoproliferative small intestinal disease'),
('9765/1', 'monoclonal gammopathy of undetermined significance'),
('9766/1', 'angiocentric immunoproliferative lesion'),
('9767/1', 'angioimmunoblastic lymphadenopathy (AIL)'),
('9768/1', 'T-gamma lymphoproliferative disease'),
('9769/1', 'immunoglobulin deposition disease'),
('9800/3', 'leukemia, nos'),
('9801/3', 'acute leukemia, nos'),
('9805/3', 'acute biphenotypic leukemia'),
('9820/3', 'lymphoid leukemia, nos'),
('9823/3', 'B-cell chronic lymphocytic leukemia/small lymphocytic lymphoma (see also M-9670/3)'),
('9826/3', 'burkitt cell leukemia (see also M-9687/3)'),
('9827/3', 'adult T-cell leukemia/lymphoma (HTLV-1 positive), includes all variants'),
('9831/1', 'T-cell large granular lymphocytic leukemia'),
('9832/3', 'prolymphocytic leukemia, nos'),
('9833/3', 'prolymphocytic leukemia, B-cell type'),
('9834/3', 'prolymphocytic leukemia, T-cell type'),
('9835/3', 'precursor cell lymphoblastic leukemia, nos (see also M-9727/3)'),
('9836/3', 'precursor B-cell lymphoblastic leukemia (see also M-9728/3)'),
('9837/3', 'precursor T-cell lymphoblastic leukemia (see also M-9729/3)'),
('9840/3', 'acute myeloid leukemia, M6 type'),
('9860/3', 'myeloid leukemia, nos'),
('9861/3', 'acute myeloid leukemia, nos (FAB or WHO type not specified) (see also M-9930/3)'),
('9863/3', 'chronic myeloid leukemia, nos'),
('9866/3', 'acute promyelocytic leukemia, t(15;17)(q22;q11-12)'),
('9867/3', 'acute myelomonocytic leukemia'),
('9870/3', 'acute basophilic leukemia'),
('9871/3', 'acute myeloid leukemia with abnormal marrow eosinophils, includes all variants'),
('9872/3', 'acute myeloid leukemia, minimal differentiation'),
('9873/3', 'acute myeloid leukemia without maturation'),
('9874/3', 'acute myeloid leukemia with maturation'),
('9875/3', 'chronic myelogenous leukemia, BCR/ABL positive'),
('9876/3', 'atypical chronic myeloid leukemia, BCR/ABL negative'),
('9891/3', 'acute monocytic leukemia'),
('9895/3', 'acute myeloid leukemia with multilineage dysplasia'),
('9896/3', 'acute myeloid leukemia, t(8;21)(q22;q22)'),
('9897/3', 'acute myeloid leukemia, 11q23 abnormalities'),
('9910/3', 'acute megakaryoblastic leukemia'),
('9920/3', 'therapy-related acute myeloid leukemia, nos'),
('9930/3', 'myeloid sarcoma (see also M-9861/3)'),
('9931/3', 'acute panmyelosis with myelofibrosis'),
('9940/3', 'hairy cell leukemia'),
('9945/3', 'chronic myelomonocytic leukemia, nos'),
('9946/3', 'juvenile myelomonocytic leukemia'),
('9948/3', 'aggressive NK-cell leukemia'),
('9950/3', 'polycythemia vera'),
('9960/3', 'chronic myeloproliferative disease, nos'),
('9961/3', 'myelosclerosis with myeloid metaplasia'),
('9962/3', 'essential thrombocythemia'),
('9963/3', 'chronic neutrophilic leukemia'),
('9964/3', 'hypereosinophilic syndrome'),
('9970/1', 'lymphoproliferative disorder, nos'),
('9975/1', 'myeloproliferative disease, nos'),
('9980/3', 'refractory anemia'),
('9982/3', 'refractory anemia with sideroblasts'),
('9983/3', 'refractory anemia with excess blasts'),
('9984/3', 'refractory anemia with excess blasts in transformation [obs]'),
('9985/3', 'refractory cytopenia with multilineage dysplasia'),
('9986/3', 'myelodysplastic syndrome with 5q deletion (5q-) syndrome'),
('9987/3', 'therapy-related myelodysplastic syndrome, nos'),
('9989/3', 'myelodysplastic syndrome, nos');

INSERT INTO `structure_value_domains` (`id` ,`domain_name` ,`override` ,`category` ,`source`)VALUES 
(NULL , 'morphology', 'open', '', 'Clinicalannotation.DiagnosisMaster::getMorphologyValues');

UPDATE structure_fields SET `type`='select', structure_value_domain=(SELECT id FROM structure_value_domains WHERE domain_name='morphology'), `setting`='' 
WHERE model='DiagnosisMaster' AND tablename='diagnosis_masters' AND field='morphology';

TRUNCATE `acos`;

UPDATE structure_formats SET `flag_edit_readonly`='0' WHERE structure_id=(SELECT id FROM structures WHERE alias='groups') AND structure_field_id=(SELECT id FROM structure_fields WHERE model='Group' AND tablename='groups' AND field='bank_id');
